name: Keystone CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  should_run_tests:
    name: Should run tests
    runs-on: ubuntu-22.04
    outputs:
      shouldRunTests: ${{ env.SHOULD_RUN_TESTS }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        if: github.event_name == 'pull_request'
        with:
          filters: |
            shouldRunTests:
              - '!{{website,docs,examples}/**,**/*.md}'
      - run: echo "SHOULD_RUN_TESTS=$SHOULD_RUN" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'
        env:
          SHOULD_RUN: ${{ steps.filter.outputs.shouldRunTests }}
      - run: echo "SHOULD_RUN_TESTS=true" >> $GITHUB_ENV
        if: github.event_name != 'pull_request'

  api-tests:
    name: API Tests
    needs: should_run_tests
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16.8
        env:
          POSTGRES_USER: keystone5
          POSTGRES_PASSWORD: k3yst0n3
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
    env:
      DATABASE_URL: 'postgres://keystone5:k3yst0n3@localhost:5432/test_db'
    strategy:
      fail-fast: false
      matrix:
        index: [0, 1, 2, 3, 4, 5, 6, 7, 8]
        adapter: ['mongoose', 'knex', 'prisma_postgresql']
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        if: needs.should_run_tests.outputs.shouldRunTests == 'true'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        if: needs.should_run_tests.outputs.shouldRunTests == 'true'
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --immutable
        if: needs.should_run_tests.outputs.shouldRunTests == 'true'
      - name: Build packages
        run: yarn build
        if: needs.should_run_tests.outputs.shouldRunTests == 'true'
      - name: Unit tests
        if: needs.should_run_tests.outputs.shouldRunTests == 'true'
        run: yarn jest --ci --maxWorkers=1 api-tests --forceExit
        env:
          CLOUDINARY_CLOUD_NAME: keystone-cloudinary
          CLOUDINARY_KEY: 758252673115372
          CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
          CI_NODE_TOTAL: 9
          CI_NODE_INDEX: ${{ matrix.index }}
          TEST_ADAPTER: ${{ matrix.adapter }}
          IFRAMELY_API_KEY: ${{ secrets.IFRAMELY_API_KEY }}
          UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY}}
          UNSPLASH_SECRET: ${{ secrets.UNSPLASH_SECRET}}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

  non-api-tests:
    name: Package Unit Tests
    needs: should_run_tests
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16.8
        env:
          POSTGRES_USER: keystone5
          POSTGRES_PASSWORD: k3yst0n3
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
    env:
      DATABASE_URL: 'postgres://keystone5:k3yst0n3@localhost:5432/test_db'
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --immutable
      - name: Build packages
        run: yarn build
      - name: Unit tests
        run: yarn jest --ci --maxWorkers=1 --testPathIgnorePatterns=api-tests --forceExit
        env:
          CLOUDINARY_CLOUD_NAME: keystone-cloudinary
          CLOUDINARY_KEY: 758252673115372
          CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}

  linting:
    name: Linting
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --immutable
      - name: Prettier
        run: yarn lint:prettier
      - name: Preconstruct (build packages)
        run: yarn build
      - name: ESLint
        run: yarn lint:eslint
      - name: TypeScript
        run: yarn lint:types
      - name: Remark
        run: yarn lint:markdown

  cypress:
    name: Cypress tests
    needs: should_run_tests
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16.8
        env:
          POSTGRES_USER: keystone5
          POSTGRES_PASSWORD: k3yst0n3
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
    env:
      DATABASE_URL: 'postgres://keystone5:k3yst0n3@localhost:5432/test_db'
      PORT: 3000
    strategy:
      fail-fast: false
      matrix:
        project:
          - test-projects/basic
          - test-projects/login
          - test-projects/access-control
          - test-projects/client-validation
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout Repo
        if: needs.should_run_tests.outputs.shouldRunTests == 'true'
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        if: needs.should_run_tests.outputs.shouldRunTests == 'true'
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --immutable
      - name: Build packages
        run: yarn build
        if: needs.should_run_tests.outputs.shouldRunTests == 'true'
      - run: yarn --cwd tests/${{ matrix.project }} cypress install
        if: needs.should_run_tests.outputs.shouldRunTests == 'true'
      - run: yarn --cwd tests/${{ matrix.project }} cypress:run:ci
        if: needs.should_run_tests.outputs.shouldRunTests == 'true'
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
